###################
# AANPAK
###################

1. Uploaden XMI
2. Uitvoeren: "Create model from MIM"
3. Voer de queries uit m.b.t. het opschonen van het MIM model
4. Ga naar "Edit MIM model", fix prefixes en sla deze op als mim/model-mim-ld.ttl
5. Uitvoeren: "Create model from MIM"
6. Voer de queries uit m.b.t. het opschonen van het model (dwz: de ontologie)
7. Ga naar "Edit model", fix prefixes en sla deze op als rdf/ontologie.ttl
8. Ga naar Download, Grafische weergave (technische namen) en sla yEd plaatje op als rdf/ontologie.graphml en rdf/ontologie.png
9. Herlaad het model, voer de queries uit voor de shapesgraph en query verwijderen string datatype (onder Model opschonen)
10. Ga naar "Edit model", fix prefixes en sla deze op als shapesgraph.ttl
11. Herlaad het model, voer de queries uit voor de owl-rdfs en query verwijderen string datatype (onder Model opschonen)
12. Ga naar "Edit model", fix prefixes en sla deze op als owl-rdfs-ontologie.ttl

###################
# Model opschonen
###################

# Verwijder string datatype
#
delete {
  graph <http://localhost:8080/data2model/container/model> {
    ?s ?p ?strliteral
  }
}
insert {
  graph <http://localhost:8080/data2model/container/model> {
    ?s ?p ?literal
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s ?p ?strliteral
    FILTER (datatype(?strliteral) = xsd:string)
    BIND (str(?strliteral) as ?literal)
  }
}

# Verwijderen rdfs:seeAlso
#
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
  graph <http://localhost:8080/data2model/container/model> {
  	?s rdfs:seeAlso ?uml
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s rdfs:seeAlso ?uml
  }
}

###################
# MIM opschonen
###################

# Verwijder rdfs:seeAlso
#
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s rdfs:seeAlso ?r
  }
}
where {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s rdfs:seeAlso ?r
  }
}

# Verwijder Kadaster-specifiek gebruik van opmaak in definities
#
prefix mim: <http://bp4mc2.org/def/mim#>
delete {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s mim:definitie ?def
  }
}
insert {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s mim:definitie ?definitie
  }
}
where {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s mim:definitie ?def
	BIND (replace(replace(replace(replace(replace(?def,"---IMKAD---\n",""),"--Definitie--\n",""),"--Toelichting--(\n.*)*$",""),"^[\n| ]+",""),"[\n| ]+$","") as ?definitie)
  }
}

# Verwijder lege definities
#
prefix mim: <http://bp4mc2.org/def/mim#>
delete {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s mim:definitie ""
  }
}
where {
  graph <http://localhost:8080/data2model/container/mim> {
    ?s mim:definitie ""
  }
}

###################
# shapesgraph maken
###################

# Verwijder owl:DatatypeProperty en owl:ObjectProperty
#
PREFIX owl: <http://www.w3.org/2002/07/owl#>
delete {
  graph <http://localhost:8080/data2model/container/model> {
	?s ?p ?o
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s ?p ?o.
    ?s a ?t
  FILTER (?t = owl:ObjectProperty || ?t = owl:DatatypeProperty)
  }
}

# Verwijder owl:Class typering
#
PREFIX owl: <http://www.w3.org/2002/07/owl#>
delete {
  graph <http://localhost:8080/data2model/container/model> {
  	?s a owl:Class.
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s a owl:Class.
  }
}

###################
# owl-rdfs ontologie maken
###################

# Verwijder sh:NodeShape typering
#
prefix sh: <http://www.w3.org/ns/shacl#>
delete {
  graph <http://localhost:8080/data2model/container/model> {
  	?s a sh:NodeShape.
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s a sh:NodeShape.
  }
}

# Omzetten shacl naar rdfs:domain en rdfs:range
#
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
insert {
  graph <http://localhost:8080/data2model/container/model> {
    ?property rdfs:domain ?domain.
    ?property rdfs:range ?range.
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s sh:targetClass ?domain.
    ?s sh:property ?ps.
    ?ps sh:path ?property.
    OPTIONAL {?ps sh:class ?range}
  }
}

# Verwijder sh:PropertyShape
#
prefix sh: <http://www.w3.org/ns/shacl#>
delete {
  graph <http://localhost:8080/data2model/container/model> {
    ?s ?p ?o
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s ?p ?o.
    ?s a sh:PropertyShape
  }
}

# Verwijder shacl elementen uit owl:Class specificatie
prefix sh: <http://www.w3.org/ns/shacl#>
delete {
  graph <http://localhost:8080/data2model/container/model> {
    ?s sh:name ?name.
    ?s sh:targetClass ?class.
    ?s sh:property ?prop.
  }
}
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s sh:name ?name.
    ?s sh:targetClass ?class.
    OPTIONAL {?s sh:property ?prop}
  }
}

###########
# Controles
###########

# Classes uit het voorbeeld (voorbeeld zit in /data)
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?t ?tlabel
where {
  graph <http://localhost:8080/data2model/container/data> {
    ?s a ?t
  }
  OPTIONAL {
    graph <http://localhost:8080/data2model/container/model> {
      ?t rdfs:label ?tlabel
    }
  }
}

# Properties uit het voorbeeld (voorbeeld zit in /data)
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?t ?p
where {
  graph <http://localhost:8080/data2model/container/data> {
    ?s ?p ?o
    OPTIONAL {?s a ?t}.
    FILTER (?p!=rdf:type)
  }
  FILTER NOT EXISTS {
    graph <http://localhost:8080/data2model/container/model> {
      ?p rdfs:label ?plabel
    }
  }
}

# Link naar de begrippen (begrippen zijn opgenomen in /data)
select distinct ?s ?begrip
where {
  graph <http://localhost:8080/data2model/container/model> {
    ?s dct:subject ?begrip
  }
  FILTER NOT EXISTS {
    graph <http://localhost:8080/data2model/container/data> {
      ?begrip a skos:Concept
    }
  }
}
